services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - pocketbase
    networks:
      - stock-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "caddy:80"
      - "--log=stdout"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - caddy
    networks:
      - stock-network

  api:
    build: ./backend
    env_file: ./backend/.env
    expose:
      - "8000"
    depends_on:
      - pocketbase
    volumes:
      - ./backend/app:/app/app
    networks:
      - stock-network
    environment:
      POCKETBASE_ADMIN_EMAIL: ${POCKETBASE_EMAIL:-admin@stock.local}
      POCKETBASE_ADMIN_PASSWORD: ${POCKETBASE_PASSWORD:-VotreSuperMotDePasseSecurisé123!}

  pocketbase:
    build: ./pocketbase
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/init_collections.py:/pb/init_collections.py:ro
      - ./pocketbase/stock_initial.csv:/pb/stock_initial.csv:ro
      - ./pocketbase/cost_mapping.csv:/pb/cost_mapping.csv:ro
    environment:
      POCKETBASE_URL: http://localhost:8090
      POCKETBASE_ADMIN_EMAIL: admin@stock.local
      POCKETBASE_ADMIN_PASSWORD: VotreSuperMotDePasseSecurisé123!
    expose:
      - "8090"
    networks:
      - stock-network
    command:
      - /bin/sh
      - -c
      - |
        /pb/pocketbase serve --http=0.0.0.0:8090 &
        PB_PID=$$!
        sleep 10
        
        echo '🔐 Création/vérification admin...'
        /pb/pocketbase admin create admin@stock.local VotreSuperMotDePasseSecurisé123! 2>&1 || echo '✅ Admin existe déjà'
        
        if command -v python3 >/dev/null 2>&1; then
          echo '📋 Vérification des fichiers CSV...'
          ls -lh /pb/*.csv 2>&1 || echo 'Pas de CSV'
          echo '--- stock_initial.csv ---'
          head -2 /pb/stock_initial.csv 2>&1 || echo 'Fichier manquant'
          echo '--- cost_mapping.csv ---'
          head -2 /pb/cost_mapping.csv 2>&1 || echo 'Fichier manquant'
          echo '🚀 Lancement init_collections.py...'
          cd /pb && python3 init_collections.py 2>&1 || echo '❌ Init collections échoué'
        fi
        
        wait $PB_PID

networks:
  stock-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: