services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - pocketbase
    networks:
      - stock-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "caddy:80"
      - "--log=stdout"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"  # Ngrok web UI
    depends_on:
      - caddy
    networks:
      - stock-network

  api:
    build: ./backend
    env_file: ./backend/.env
    expose:
      - "8000"
    depends_on:
      - pocketbase
    volumes:
      - ./backend/app:/app/app
    networks:
      - stock-network
    environment:
      POCKETBASE_ADMIN_EMAIL: ${POCKETBASE_ADMIN_EMAIL:-admin@stock.local}
      POCKETBASE_ADMIN_PASSWORD: ${POCKETBASE_ADMIN_PASSWORD:-Admin123!}

  pocketbase:
    build: ./pocketbase
    environment:
      POCKETBASE_URL: "http://localhost:8090"
      POCKETBASE_EMAIL: "admin@example.com"
      POCKETBASE_PASSWORD: "admin123456789"
    expose:
      - "8090"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
    command: >
      sh -c "./pocketbase serve --http 0.0.0.0:8090 &
             PB_PID=$$!;
             until curl -sf http://localhost:8090/api/health >/dev/null 2>&1; do
               echo 'waiting pocketbase...'; sleep 1;
             done;
             python3 /pb/init_collections.py;
             wait $$PB_PID"
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
